# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0002_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the Participant', verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phoneNumber', models.IntegerField(unique=True, verbose_name='phone number')),
                ('college', models.TextField(help_text='College of the participant', verbose_name='college')),
                ('stream', models.TextField(help_text='Stream of the Participant', verbose_name='stream')),
                ('subregion', models.TextField(help_text='Subregion of the Participant', verbose_name='subregion')),
                ('zone', models.TextField(help_text='Zone of the Participant', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
