# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0003_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='dob',
            field=models.DateField(blank=True, help_text='event date', null=True, verbose_name='date of birth'),
        ),
    ]
